"""add style schedules

Revision ID: 1db393e78336
Revises: g1h2i3j4k5l6
Create Date: 2025-12-23 08:59:09.803080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db393e78336'
down_revision = 'g1h2i3j4k5l6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_schedules_style_name'), ['style_name'], unique=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('excerpt',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('style_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_schedules_style_name'))

    op.drop_table('style_schedules')
    # ### end Alembic commands ###
