"""add is_edited to comments

Revision ID: 54172c430509
Revises: b2c4d6e8f0a1
Create Date: 2025-12-22 10:29:58.796902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54172c430509'
down_revision = 'b2c4d6e8f0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_edited')
    # ### end Alembic commands ###
