"""Add deactivated_at to User and update cascades

Revision ID: 970298341ca4
Revises: f974fc3bdece
Create Date: 2025-12-19 09:05:01.765528

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = '970298341ca4'
down_revision = 'f974fc3bdece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_meetings_commission_id'), ['commission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_meetings_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_meetings_start_at'), ['start_at'], unique=False)

    with op.batch_alter_table('commission_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_memberships_commission_id'), ['commission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_memberships_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_memberships_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('commission_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_projects_commission_id'), ['commission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_projects_status'), ['status'], unique=False)

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('commissions_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_commissions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_commissions_slug'), ['slug'], unique=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category'), ['category'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_key'), ['key'], unique=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=False)
        batch_op.alter_column('excerpt',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('cover_image',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.TEXT(),
               type_=app.models.EncryptedType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('deactivated_at')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('excerpt',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_key'))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_category'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=app.models.EncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commissions_slug'))
        batch_op.drop_index(batch_op.f('ix_commissions_name'))
        batch_op.drop_index(batch_op.f('ix_commissions_is_active'))
        batch_op.create_unique_constraint(batch_op.f('commissions_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('commission_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_projects_status'))
        batch_op.drop_index(batch_op.f('ix_commission_projects_commission_id'))

    with op.batch_alter_table('commission_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_commission_memberships_role'))
        batch_op.drop_index(batch_op.f('ix_commission_memberships_commission_id'))

    with op.batch_alter_table('commission_meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_meetings_start_at'))
        batch_op.drop_index(batch_op.f('ix_commission_meetings_end_at'))
        batch_op.drop_index(batch_op.f('ix_commission_meetings_commission_id'))

    # ### end Alembic commands ###
