"""add_is_public_to_events

Revision ID: cda65ecd4c01
Revises: 9f8e7d6c5b4a
Create Date: 2026-01-01 13:13:10.186118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda65ecd4c01'
down_revision = '9f8e7d6c5b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_public', sa.Boolean(), nullable=True))
    # Establecer todos los eventos existentes como públicos por defecto
    op.execute("UPDATE events SET is_public = true WHERE is_public IS NULL")
    # Hacer el campo NOT NULL después de establecer valores
    op.alter_column('events', 'is_public', nullable=False, server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_public')
    # ### end Alembic commands ###
